### ISSUE TITLE
500 internal server error on 411.image-recognition benchmark 

### ISSUE THREAD

**Issue by jchigu** [spcl/serverless-benchmarks#123] opened 2023-02-21 20:07 UTC
(python-venv) jchigu@SEBS:~$ curl 172.17.0.3:9000 --request POST -o testresult411imagerecognition.json --data '{"bucket": {                   
        "input": "411.image-recognition-1-input-c12339db-5c8f-44",
        "model": "411.image-recognition-0-input-3d81938b-b77a-45"
      },
      "object": {
        "input": "800px-Porsche_991_silver_IAA.jpg",
        "model": "resnet50-19c8e357.pth"
      }
}' --header 'Content-Type: application/json'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2385  100  2109  100   276   3716    486 --:--:-- --:--:-- --:--:--  4328
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 500 Internal Server Error</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 500 Internal Server Error</h1>
            <p>Sorry, the requested URL <tt>&#039;http://172.17.0.3:9000/&#039;</tt>
               caused an error:</p>
            <pre>Internal Server Error</pre>
              <h2>Exception:</h2>
              <pre>TypeError()</pre>
              <h2>Traceback:</h2>
              <pre>Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.7/site-packages/minio/helpers.py&quot;, line 219, in check_non_empty_string
    if not string.strip():
AttributeError: &#039;NoneType&#039; object has no attribute &#039;strip&#039;

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.7/site-packages/bottle.py&quot;, line 868, in _handle
    return route.call(**args)
  File &quot;/usr/local/lib/python3.7/site-packages/bottle.py&quot;, line 1748, in wrapper
    rv = callback(*a, **ka)
  File &quot;/sebs/server.py&quot;, line 17, in flush_log
    ret = function.handler(request.json)
  File &quot;/function/function/function.py&quot;, line 72, in handler
    client.download(input_bucket, key, download_path)
  File &quot;/function/function/storage.py&quot;, line 37, in download
    self.client.fget_object(bucket, file, filepath)
  File &quot;/usr/local/lib/python3.7/site-packages/minio/api.py&quot;, line 1025, in fget_object
    check_non_empty_string(object_name)
  File &quot;/usr/local/lib/python3.7/site-packages/minio/helpers.py&quot;, line 222, in check_non_empty_string
    raise TypeError() from exc
TypeError
</pre>
        </body>
    </html>

**Comment by mcopik** [comment] 2023-02-22 14:47
@jchigu Unfortunately, I cannot reproduce the issue. The stack trace indicates that the call to `fget_object` on Minio was done with an object name `None` and not `str`.

Can you please restart the function container and verify that the issue persists?

**Comment by mcopik** [comment] 2023-03-02 11:53
@jchigu Does this issue still appear? If yes, then can you please provide more information?

**Comment by mcopik** [comment] 2023-03-06 12:46
Closing down - if the issue still persists, then please reopen with updated information instead of opening new ones.

**Closed by mcopik** 2023-03-06 12:46 UTC
Labels: needs-reproduction
