### ISSUE TITLE
regression test error

### ISSUE THREAD

**Issue by jchigu** [spcl/serverless-benchmarks#127] opened 2023-03-02 10:46 UTC
(python-venv) jchigu@SeBS:~/serverless-benchmarks$ ./install.py --aws --azure --gcp --openwhisk --local
Using existing Python virtualenv at python-venv
Install Python dependencies with pip
Install Python dependencies for AWS
Install Python dependencies for Azure
Install Python dependencies for GCP
Install Python dependencies for local
Initialize Docker image for local storage.
Download benchmarks data
(python-venv) jchigu@SeBS:~/serverless-benchmarks$ ./sebs.py benchmark regression test --config config/example.json --deployment aws
Select test test_110.dynamic-html
Select test test_120.uploader
Select test test_210.thumbnailer
Select test test_220.video-processing
Select test test_311.compression
Select test test_411.image-recognition
Select test test_501.graph-pagerank
Select test test_502.graph-mst
Select test test_503.graph-bfs
Select test test_504.dna-visualisation

-------------

sebs.regression.AWSTestSequence.test_110.dynamic-html: fail
sebs.regression.AWSTestSequence.test_110.dynamic-html: Traceback (most recent call last):
  File "/home/jchigu/serverless-benchmarks/sebs/regression.py", line 38, in test
    deployment_client = self.get_deployment(benchmark_name)
  File "/home/jchigu/serverless-benchmarks/sebs/regression.py", line 103, in get_deployment
    deployment_client = self.client.get_deployment(
  File "/home/jchigu/serverless-benchmarks/sebs/sebs.py", line 106, in get_deployment
    raise RuntimeError("Deployment {name} not supported!".format(name=name))
RuntimeError: Deployment aws not supported!

-------------

-------------

sebs.regression.AWSTestSequence.test_120.uploader: fail
sebs.regression.AWSTestSequence.test_120.uploader: Traceback (most recent call last):
  File "/home/jchigu/serverless-benchmarks/sebs/regression.py", line 38, in test
    deployment_client = self.get_deployment(benchmark_name)
  File "/home/jchigu/serverless-benchmarks/sebs/regression.py", line 103, in get_deployment
    deployment_client = self.client.get_deployment(
  File "/home/jchigu/serverless-benchmarks/sebs/sebs.py", line 106, in get_deployment
    raise RuntimeError("Deployment {name} not supported!".format(name=name))
RuntimeError: Deployment aws not supported!

-------------

-------------

sebs.regression.AWSTestSequence.test_210.thumbnailer: fail
sebs.regression.AWSTestSequence.test_210.thumbnailer: Traceback (most recent call last):
  File "/home/jchigu/serverless-benchmarks/sebs/regression.py", line 38, in test
    deployment_client = self.get_deployment(benchmark_name)
  File "/home/jchigu/serverless-benchmarks/sebs/regression.py", line 103, in get_deployment
    deployment_client = self.client.get_deployment(
  File "/home/jchigu/serverless-benchmarks/sebs/sebs.py", line 106, in get_deployment
    raise RuntimeError("Deployment {name} not supported!".format(name=name))
RuntimeError: Deployment aws not supported!

-------------

-------------

sebs.regression.AWSTestSequence.test_220.video-processing: fail
sebs.regression.AWSTestSequence.test_220.video-processing: Traceback (most recent call last):
  File "/home/jchigu/serverless-benchmarks/sebs/regression.py", line 38, in test
    deployment_client = self.get_deployment(benchmark_name)
  File "/home/jchigu/serverless-benchmarks/sebs/regression.py", line 103, in get_deployment
    deployment_client = self.client.get_deployment(
  File "/home/jchigu/serverless-benchmarks/sebs/sebs.py", line 106, in get_deployment
    raise RuntimeError("Deployment {name} not supported!".format(name=name))
RuntimeError: Deployment aws not supported!

-------------

-------------

sebs.regression.AWSTestSequence.test_311.compression: fail
sebs.regression.AWSTestSequence.test_311.compression: Traceback (most recent call last):
  File "/home/jchigu/serverless-benchmarks/sebs/regression.py", line 38, in test
    deployment_client = self.get_deployment(benchmark_name)
  File "/home/jchigu/serverless-benchmarks/sebs/regression.py", line 103, in get_deployment
    deployment_client = self.client.get_deployment(
  File "/home/jchigu/serverless-benchmarks/sebs/sebs.py", line 106, in get_deployment
    raise RuntimeError("Deployment {name} not supported!".format(name=name))
RuntimeError: Deployment aws not supported!

-------------

-------------

sebs.regression.AWSTestSequence.test_411.image-recognition: fail
sebs.regression.AWSTestSequence.test_411.image-recognition: Traceback (most recent call last):
  File "/home/jchigu/serverless-benchmarks/sebs/regression.py", line 38, in test
    deployment_client = self.get_deployment(benchmark_name)
  File "/home/jchigu/serverless-benchmarks/sebs/regression.py", line 103, in get_deployment
    deployment_client = self.client.get_deployment(
  File "/home/jchigu/serverless-benchmarks/sebs/sebs.py", line 106, in get_deployment
    raise RuntimeError("Deployment {name} not supported!".format(name=name))
RuntimeError: Deployment aws not supported!

-------------

-------------

sebs.regression.AWSTestSequence.test_501.graph-pagerank: fail
sebs.regression.AWSTestSequence.test_501.graph-pagerank: Traceback (most recent call last):
  File "/home/jchigu/serverless-benchmarks/sebs/regression.py", line 38, in test
    deployment_client = self.get_deployment(benchmark_name)
  File "/home/jchigu/serverless-benchmarks/sebs/regression.py", line 103, in get_deployment
    deployment_client = self.client.get_deployment(
  File "/home/jchigu/serverless-benchmarks/sebs/sebs.py", line 106, in get_deployment
    raise RuntimeError("Deployment {name} not supported!".format(name=name))
RuntimeError: Deployment aws not supported!

-------------

-------------

sebs.regression.AWSTestSequence.test_502.graph-mst: fail
sebs.regression.AWSTestSequence.test_502.graph-mst: Traceback (most recent call last):
  File "/home/jchigu/serverless-benchmarks/sebs/regression.py", line 38, in test
    deployment_client = self.get_deployment(benchmark_name)
  File "/home/jchigu/serverless-benchmarks/sebs/regression.py", line 103, in get_deployment
    deployment_client = self.client.get_deployment(
  File "/home/jchigu/serverless-benchmarks/sebs/sebs.py", line 106, in get_deployment
    raise RuntimeError("Deployment {name} not supported!".format(name=name))
RuntimeError: Deployment aws not supported!

-------------

-------------

sebs.regression.AWSTestSequence.test_503.graph-bfs: fail
sebs.regression.AWSTestSequence.test_503.graph-bfs: Traceback (most recent call last):
  File "/home/jchigu/serverless-benchmarks/sebs/regression.py", line 38, in test
    deployment_client = self.get_deployment(benchmark_name)
  File "/home/jchigu/serverless-benchmarks/sebs/regression.py", line 103, in get_deployment
    deployment_client = self.client.get_deployment(
  File "/home/jchigu/serverless-benchmarks/sebs/sebs.py", line 106, in get_deployment
    raise RuntimeError("Deployment {name} not supported!".format(name=name))
RuntimeError: Deployment aws not supported!

-------------

-------------

sebs.regression.AWSTestSequence.test_504.dna-visualisation: fail
sebs.regression.AWSTestSequence.test_504.dna-visualisation: Traceback (most recent call last):
  File "/home/jchigu/serverless-benchmarks/sebs/regression.py", line 38, in test
    deployment_client = self.get_deployment(benchmark_name)
  File "/home/jchigu/serverless-benchmarks/sebs/regression.py", line 103, in get_deployment
    deployment_client = self.client.get_deployment(
  File "/home/jchigu/serverless-benchmarks/sebs/sebs.py", line 106, in get_deployment
    raise RuntimeError("Deployment {name} not supported!".format(name=name))
RuntimeError: Deployment aws not supported!

-------------

Succesfully executed 0 out of 10 functions
Failures when executing 10 out of 10 functions
- 501.graph-pagerank
- 311.compression
- 120.uploader
- 210.thumbnailer
- 503.graph-bfs
- 220.video-processing
- 504.dna-visualisation
- 502.graph-mst
- 110.dynamic-html
- 411.image-recognition
(python-venv) jchigu@SeBS:~/serverless-benchmarks$

**Comment by mcopik** [comment] 2023-03-02 11:51
Duplicate of #125

**Closed by mcopik** 2023-03-02 11:51 UTC
