### ISSUE TITLE
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions".

### ISSUE THREAD

**Issue by jchigu** [spcl/serverless-benchmarks#135] opened 2023-03-05 20:21 UTC
(python-venv) justinchigu@SeBSVM:~/serverless-benchmarks$ ./sebs.py benchmark regression test --config config/example.json --deployment aws --benchmark-name 504.dna-visualisation
Skip test test_110.dynamic-html
Skip test test_120.uploader
Skip test test_210.thumbnailer
Skip test test_220.video-processing
Skip test test_311.compression
Skip test test_411.image-recognition
Skip test test_501.graph-pagerank
Skip test test_502.graph-mst
Skip test test_503.graph-bfs
Select test test_504.dna-visualisation
Begin regression test of 504.dna-visualisation on aws, region: us-east-1.

-------------

sebs.regression.AWSTestSequence.test_504.dna-visualisation: fail
sebs.regression.AWSTestSequence.test_504.dna-visualisation: Traceback (most recent call last):
  File "/home/justinchigu/serverless-benchmarks/sebs/aws/aws.py", line 176, in create_function
    ret = self.client.get_function(FunctionName=func_name)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetFunction operation: Function not found: arn:aws:lambda:us-east-1:702948139887:function:504_dna_visualisation_python_3_7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/justinchigu/serverless-benchmarks/sebs/regression.py", line 50, in test
    func = deployment_client.get_function(
  File "/home/justinchigu/serverless-benchmarks/sebs/faas/system.py", line 174, in get_function
    function = self.create_function(code_package, func_name)
  File "/home/justinchigu/serverless-benchmarks/sebs/aws/aws.py", line 211, in create_function
    ret = self.client.create_function(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/client.py", line 943, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/client.py", line 966, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/httpsession.py", line 494, in send
    raise ConnectionClosedError(
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions".

-------------

Succesfully executed 0 out of 1 functions
Failures when executing 1 out of 1 functions
- 504.dna-visualisation
(python-venv) justinchigu@SeBSVM:~/serverless-benchmarks$

**Comment by mcopik** [comment] 2023-03-06 13:11
This is a duplicate of #129.

**Closed by mcopik** 2023-03-06 13:11 UTC
