### ISSUE TITLE
Access Key for 504.dna-visualisation does not exit on our records

### ISSUE THREAD

**Issue by jchigu** [spcl/serverless-benchmarks#121] opened 2023-02-21 18:58 UTC
(python-venv) jchigu@SEBS:~$ curl 172.17.0.3:9000 --request POST -o testresult504dnavisualisation.json --data '{"bucket": {                                 
        "input": "504.dna-visualisation-0-input-626b04ac-f27a-48",
        "output": "504.dna-visualisation-0-output-d65a6e48-fbaf-4e"
      },
      "object": {
        "key": "bacillus_subtilis.fasta"
      }
}' --header 'Content-Type: application/json'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3048  100  2823  100   225   3498    278 --:--:-- --:--:-- --:--:--  3922
(python-venv) jchigu@SEBS:~$ firefox ./testresult504dnavisualisation.json

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 500 Internal Server Error</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 500 Internal Server Error</h1>
            <p>Sorry, the requested URL <tt>&#039;http://172.17.0.3:9000/&#039;</tt>
               caused an error:</p>
            <pre>Internal Server Error</pre>
              <h2>Exception:</h2>
              <pre>S3Error(&#039;S3 operation failed; code: InvalidAccessKeyId, message: The Access Key Id you provided does not exist in our records., resource: /504.dna-visualisation-0-input-626b04ac-f27a-48, request_id: 1745EBAA84C46841, host_id: f437d121-bb9f-4085-8be4-7cbab12cacf2, bucket_name: 504.dna-visualisation-0-input-626b04ac-f27a-48&#039;)</pre>
              <h2>Traceback:</h2>
              <pre>Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.7/site-packages/bottle.py&quot;, line 868, in _handle
    return route.call(**args)
  File &quot;/usr/local/lib/python3.7/site-packages/bottle.py&quot;, line 1748, in wrapper
    rv = callback(*a, **ka)
  File &quot;/sebs/server.py&quot;, line 17, in flush_log
    ret = function.handler(request.json)
  File &quot;/function/function/function.py&quot;, line 72, in handler
    client.download(input_bucket, key, download_path)
  File &quot;/function/function/storage.py&quot;, line 37, in download
    self.client.fget_object(bucket, file, filepath)
  File &quot;/usr/local/lib/python3.7/site-packages/minio/api.py&quot;, line 1037, in fget_object
    version_id=version_id,
  File &quot;/usr/local/lib/python3.7/site-packages/minio/api.py&quot;, line 1864, in stat_object
    query_params=query_params,
  File &quot;/usr/local/lib/python3.7/site-packages/minio/api.py&quot;, line 394, in _execute
    region = self._get_region(bucket_name, None)
  File &quot;/usr/local/lib/python3.7/site-packages/minio/api.py&quot;, line 465, in _get_region
    query_params={&quot;location&quot;: &quot;&quot;},
  File &quot;/usr/local/lib/python3.7/site-packages/minio/api.py&quot;, line 380, in _url_open
    raise response_error
minio.error.S3Error: S3 operation failed; code: InvalidAccessKeyId, message: The Access Key Id you provided does not exist in our records., resource: /504.dna-visualisation-0-input-626b04ac-f27a-48, request_id: 1745EBAA84C46841, host_id: f437d121-bb9f-4085-8be4-7cbab12cacf2, bucket_name: 504.dna-visualisation-0-input-626b04ac-f27a-48
</pre>
        </body>
    </html>

**Comment by mcopik** [comment] 2023-02-22 14:35
This seems to be a duplicate of #120 - next time, please try to group similar errors as it helps us to triage and replicate issues :-)

**Closed by mcopik** 2023-02-22 14:35 UTC
