### ISSUE TITLE
Connection was closed before we received a valid response from endpoint URL: "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions"

### ISSUE THREAD

**Issue by jchigu** [spcl/serverless-benchmarks#132] opened 2023-03-05 01:10 UTC
(python-venv) justinchigu@SeBSVM:~/serverless-benchmarks$ ./sebs.py benchmark invoke 504.dna-visualisation test --config config/example.json --deployment aws --verbose
02:56:24,627 INFO SeBS-65dc: Created experiment output at /home/justinchigu/serverless-benchmarks
02:56:25,101 INFO AWS.Credentials-9ee5: Using cached credentials for AWS
02:56:25,102 INFO AWS.Resources-704a: Using cached resources for AWS
02:56:25,103 INFO AWS.Config-26ae: Using cached config for AWS
02:56:25,233 INFO Benchmark-f1c7: Building benchmark 504.dna-visualisation. Reason: no cached code package.
02:56:26,526 INFO Benchmark-f1c7: Docker build of benchmark dependencies in container of image spcleth/serverless-benchmarks:build.aws.python.3.7
02:56:26,526 INFO Benchmark-f1c7: Docker mount of benchmark code from path /home/justinchigu/serverless-benchmarks/504.dna-visualisation_code/python/3.7
02:58:09,32 INFO AWS-5b48: Created /home/justinchigu/serverless-benchmarks/504.dna-visualisation_code/python/3.7/504.dna-visualisation.zip archive
02:58:09,33 INFO AWS-5b48: Zip archive size 46.827398 MB
02:58:09,34 INFO Benchmark-f1c7: Created code package (source hash: 45fcb5bb5cabd9e5c3b09b56fd855ed7), for run on aws with python:3.7
02:58:09,352 INFO AWS-5b48: Creating new function! Reason: function 504_dna_visualisation_python_3_7 not found in cache.
02:58:10,558 INFO AWS-5b48: Creating function 504_dna_visualisation_python_3_7 from /home/justinchigu/serverless-benchmarks/cache/504.dna-visualisation/aws/python/3.7/504.dna-visualisation.zip
ERROR:root:Connection was closed before we received a valid response from endpoint URL: "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions".
Traceback (most recent call last):
  File "/home/justinchigu/serverless-benchmarks/sebs/aws/aws.py", line 176, in create_function
    ret = self.client.get_function(FunctionName=func_name)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetFunction operation: Function not found: arn:aws:lambda:us-east-1:702948139887:function:504_dna_visualisation_python_3_7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 43, in __call__
    return self.main(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 85, in wrapper
    return func(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 110, in wrapper
    return func(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 245, in invoke
    func = deployment_client.get_function(
  File "/home/justinchigu/serverless-benchmarks/sebs/faas/system.py", line 174, in get_function
    function = self.create_function(code_package, func_name)
  File "/home/justinchigu/serverless-benchmarks/sebs/aws/aws.py", line 211, in create_function
    ret = self.client.create_function(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/client.py", line 943, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/client.py", line 966, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/httpsession.py", line 494, in send
    raise ConnectionClosedError(
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions".
INFO:Benchmark-fe11:Update cached config /home/justinchigu/serverless-benchmarks/cache/aws.json
(python-venv) justinchigu@SeBSVM:~/serverless-benchmarks$

**Comment by mcopik** [comment] 2023-03-06 12:57
@jchigu This is a duplicate of issue #129 - please create one issue per the type of problem experienced. In the future, please also follow the provided issue template.

**Closed by mcopik** 2023-03-06 12:57 UTC
