### ISSUE TITLE
Need help to go around Internal server error running benchmark 501.graph-pagerank

### ISSUE THREAD

**Issue by jchigu** [spcl/serverless-benchmarks#111] opened 2023-02-15 14:01 UTC
(python-venv) jchigu@SEBS:~$ curl 172.17.0.3:9000 --request POST -o testresult501graphpagerankbenchmark.html --data '{"size": 10}' --header 'Content-Type: application/json'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1697  100  1685  100    12  17675    125 --:--:-- --:--:-- --:--:-- 18053
(python-venv) jchigu@SEBS:~$ cat testresult501graphpagerankbenchmark.html

    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 500 Internal Server Error</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 500 Internal Server Error</h1>
            <p>Sorry, the requested URL <tt>&#039;http://172.17.0.3:9000/&#039;</tt>
               caused an error:</p>
            <pre>Internal Server Error</pre>
              <h2>Exception:</h2>
              <pre>TypeError(&quot;&#039;&lt;=&#039; not supported between instances of &#039;int&#039; and &#039;NoneType&#039;&quot;)</pre>
              <h2>Traceback:</h2>
              <pre>Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.7/site-packages/bottle.py&quot;, line 868, in _handle
    return route.call(**args)
  File &quot;/usr/local/lib/python3.7/site-packages/bottle.py&quot;, line 1748, in wrapper
    rv = callback(*a, **ka)
  File &quot;/sebs/server.py&quot;, line 17, in flush_log
    ret = function.handler(request.json)
  File &quot;/function/function/function.py&quot;, line 17, in handler
    random_numbers = sample(range(0, 1000000), size)
  File &quot;/usr/local/lib/python3.7/random.py&quot;, line 320, in sample
    if not 0 &lt;= k &lt;= n:
TypeError: &#039;&lt;=&#039; not supported between instances of &#039;int&#039; and &#039;NoneType&#039;
</pre>
        </body>
    </html>
(python-venv) jchigu@SEBS:~$

**Comment by jchigu** [comment] 2023-02-15 18:39
THIS IS MY OUT.LOG FOR 502.GRAPH-MST.  it is reporting no cached code package similar to 501.GRAPH-PAGERANK

(python-venv) jchigu@SEBS:~$ cat out.log
20:03:35,830 INFO SeBS-8e2e: Created experiment output at /home/jchigu
20:03:43,245 INFO minio.Minio-8b63: Created bucket 502.graph-mst-0-input-39ffee77-b728-47
20:03:43,324 INFO minio.Minio-8b63: Created bucket 502.graph-mst-0-output-da23d077-22d9-41
20:03:43,324 INFO Benchmark-2471: Building benchmark 502.graph-mst. Reason: no cached code package.
20:03:43,402 INFO Benchmark-2471: Docker build of benchmark dependencies in container of image spcleth/serverless-benchmarks:build.local.python.3.7
20:03:43,402 INFO Benchmark-2471: Docker mount of benchmark code from path /home/jchigu/502.graph-mst_code/python/3.7
20:09:28,216 INFO Local-d7b2: Function size 0.003906 MB
20:09:28,224 INFO Benchmark-2471: Created code package (source hash: 40f9cc4fc0199495a6d1c62c04eb52bd), for run on local with python:3.7
20:09:28,261 INFO Local-d7b2: Creating new function! Reason: function 502.graph-mst-python-3.7 not found in cache.
20:09:29,430 INFO Local-d7b2: Started 502.graph-mst-python-3.7 function at container 0bb7e4c35ea28d0c8ec5dd26995efdf597f2c7c6c97b54644a67f868902062e5 , running on 172.17.0.3:9000
20:09:29,431 INFO SeBS-8e2e: Save results to /home/jchigu/out_502graphmstbenchmark.json
(python-venv) jchigu@SEBS:~$

**Comment by mcopik** [comment] 2023-02-16 21:25
@jchigu I have verified the issue, and I was able to reproduce it. It was caused by a deprecated dependency. I opened a pull request #113, with a new branch that fixed this issue. The change should be merged with the master branch soon, but you can use the new branch immediately.

I am closing the issue as I was able to reproduce the issue, and I confirm it has been fixed. If you are still experiencing such a problem and the fix does not resolve it, then please reopen the issue.

Thanks for raising the issue! :-)

**Closed by mcopik** 2023-02-16 21:25 UTC
